-- ============================================================
-- DOCE JARDIM — SQL para criar novas tabelas no Supabase
-- ============================================================
-- Copie e execute no Editor SQL do Supabase (Dashboard > SQL Editor)
-- ============================================================

-- 1. TABELA CLIENTES (vendas fiado)
CREATE TABLE IF NOT EXISTS clientes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            TEXT NOT NULL,
    telefone        TEXT,
    endereco        TEXT,
    observacoes     TEXT,
    saldo_devedor   NUMERIC DEFAULT 0,
    data_cadastro   TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABELA PAGAMENTOS DE CLIENTES (histórico de pagamentos fiado)
CREATE TABLE IF NOT EXISTS pagamentos_clientes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id  BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    valor_pago  NUMERIC NOT NULL,
    data        TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABELA DÍZIMOS (registro mensal de 10% do lucro)
CREATE TABLE IF NOT EXISTS dizimos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mes_ano         TEXT NOT NULL,          -- ex: "Janeiro de 2026"
    total_lucro     NUMERIC NOT NULL,       -- lucro total do período
    valor_dizimo    NUMERIC NOT NULL,       -- 10% do lucro
    data_inicio     TIMESTAMPTZ NOT NULL,
    data_fim        TIMESTAMPTZ NOT NULL,
    data_registro   TIMESTAMPTZ DEFAULT NOW(),
    usuario_id      BIGINT REFERENCES usuarios(id),
    usuario_nome    TEXT
);

-- 4. ADICIONAR colunas de cliente nas vendas existentes (se não existirem)
ALTER TABLE vendas
    ADD COLUMN IF NOT EXISTS cliente_id   BIGINT,
    ADD COLUMN IF NOT EXISTS cliente_nome TEXT;

-- 5. Índices para desempenho
CREATE INDEX IF NOT EXISTS idx_clientes_saldo ON clientes(saldo_devedor);
CREATE INDEX IF NOT EXISTS idx_dizimos_mes_ano ON dizimos(mes_ano);
CREATE INDEX IF NOT EXISTS idx_pagamentos_cliente ON pagamentos_clientes(cliente_id);

-- ============================================================
-- FIM DO SQL
-- ============================================================
